language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover clover.xml

before_script:
  # Install code climate coverage reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  # Submit coverage report to codeclimate
  - if [ $(phpenv version-name) = "7.2" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build -r $CC_TEST_REPORTER_ID --exit-code $TRAVIS_TEST_RESULT; fi
